### ISSUE TITLE
acctrans sporadic demand for a binary tree

### ISSUE THREAD

**Issue by axelwilhelm** [KlausVigo/phangorn#102]
I do this:
```
a<-read.alignment("allBsaMt.fa", format="fasta")
a.phydat<-as.phyDat(a)
dist.a.phydat<-dist.dna(as.DNAbin(a.phydat))
upgma.a<-upgma(dist.a.phydat)
```
No problem, then this:
```
pars.a <- optim.parsimony(upgma.a, a.phydat, method = "sankoff")
pars.a<-acctran(pars.a, a.phydat)
```
Still no problem but if I use the fitch method:

```
pars.a <- optim.parsimony(upgma.a, a.phydat, method = "fitch") 
pars.a<-acctran(pars.a, a.phydat) 
```
**Error in ptree(tree, data, type = "ACCTRAN", retData = FALSE) :    Tree must be binary!**
If I use a smaller infile the problem does not occur

**Comment by KlausVigo** [comment]
Hi @axelwilhelm,

The reason for this is that 
```
pars.a <- optim.parsimony(upgma.a, a.phydat, method = "fitch") 
```
does some preprocessing of the data  to speed up computations. It first removes all parsimony invariant sites 
and this often results that there are identical sequences for the remaining data. 
If you have at least 3 identical sequences you can add a multifurcation for these instead of showing all the equivalent binary trees. 
So you get a polytomy 
```
    /------- A
   /
------------ B
   \
    \------- C
```
instead of one of the three following binary sub-trees
```
  /------ A
--
  \  /--- B
   \/
    \
     \--- C

  /------ B
--
  \  /--- A
   \/
    \
     \--- C

  /------ C
--
  \  /--- B
   \/
    \
     \--- A
```
For the sankoff algorithm, if the the transition rates are not symmetric, the different
binary trees do not necessarily result in the same parsimony score, so no preprocessing is done there. 
> If I use a smaller infile the problem does not occur
With larger data sets you are more likely to experience this. 

The solution to your problem is 
```
pars.a <- optim.parsimony(upgma.a, a.phydat, method = "fitch") 
pars.a <- multi2di(pars.a) # randomly resolve polytomies 
pars.a <- acctran(pars.a, a.phydat) 
```
and optionally to get rid of edges with score zero
```
pars.a <- di2multi(pars.a)
```
I will change the acctran function to check for multifurcations and avoid the error message for the next release. 

Regards, 
Klaus
