### ISSUE TITLE
Preserve internal node names in ancestral.pml

### ISSUE THREAD

**Issue by dynamiskduo** [KlausVigo/phangorn#108]
Hello :)
Thank you for a very nice package - I am enjoying the many different functions.

I am currently doing ancestral reconstruction of sequences of internal nodes. In the tree I read into R, the internal nodes are numbered in a specific way. Is there a way to preserve this numbering so that the node names are consistent when I write the sequences to a file? Or some other way of keeping tracks of which nodes are which, e.g. by showing the tree and internal node names for the reconstruction?
This is the code I run: 
```
fit_HE = optim.pml(fit_HE, model="GTR", control = pml.control(trace=0)) 
anc.ml_HE = ancestral.pml(fit_HE, "ml", return = "phyDat")
as.character(anc.ml_HE)
write.phyDat(anc.ml_HE, file = "HE_reconstructed_seqs.fasta", format = "fasta")
```
Thank you in advance!
Best,
Amanda

**Comment by KlausVigo** [comment]
Dear Amanda, 

this is the second question regarding internal nodes this week. It seems I should do something about it;)
```
tree <- fit_HE$tree
#The node labels refer to the internal numbering from ape
plot(tree)
nodelabels()
```
To fix the labels on your data set
```
names(anc.ml_HE) <- c(tree$tip.label, tree$node.label)
```
should do the trick. 
I should check if the tree has (unique) node labels and use these if available. Node labels are often misused to contain things like bootstrap values or are often missing, that's why I did not use them. 

Kind regards, 
Klaus

**Comment by dynamiskduo** [comment]
Thanks a lot for the speedy reply! 
You are a champ :D

**Comment by dynamiskduo** [comment]
And just to verify; since the tree is unrooted during optim.pml, the ancestral sequence for the root cannot be determined (not without adding an outgroup, that is) - or am I mistaken? :)
