### ISSUE TITLE
nnls.tree fails with some trees

### ISSUE THREAD

**Issue by mguzmann** [KlausVigo/phangorn#155]
I am having an issue with nnls.tree, but I'm not sure if it is a bug or an error on my side:

```
tree1 <- ape::read.tree(text = "(((((t1:1,t2:1)n5:1,(((t3:1,t4:1)n8:1,(t5:1,t6:1)n9:1)n7:1,(t7:1,(t8:1,t9:1)n11:1)n10:1)n6:1,(t10:1,t11:1,((t12:1,t13:1,t14:1)n14:1,(t15:1,t16:1,t17:1,t18:1)n15:1)n13:1)n12:1)n4:1,(((t19:1,(t20:1,(t21:1,t22:1)n20:1)n19:1)n18:1,t23:1)n17:1,(t24:1,(t25:1,t26:1)n22:1,(t27:1,t28:1,t29:1,t30:1)n23:1)n21:1)n16:1,(t31:1)n24:1,(t32:1,t33:1,t34:1)n25:1)n3:1,t35:1)n2:1)n1;")

nnls.tree(cophenetic(tree1), tree1)
```

Fails with:

`Error in fixupDN.if.valid(value, x@Dim) : length of Dimnames[[2]] (58) is not equal to Dim[2] (57)`

The issue seems to come from phangorn:::designUnrooted when building the sparse matrix.
I tried bypassing this by forcing nnls.tree to use the non-sparse version, but then I get an error at 

```
betahat <- quadprog::solve.QP.compact(as.matrix(Dmat), as.vector(dvec), 
      Amat, Aind)$sol
```

Which claims the Aind indices are wrong.

Weirdly, doing:

```
tree2 <- drop.tip(tree1, "t35")
nnls.tree(cophenetic(tree2), tree2)
```

Makes everything work fine.

**Comment by KlausVigo** [comment]
Hello @mguzmann,

thanks for your bug report. Your tree has two features, which I did not quite expect and check for. I will fix it in the next phangorn version.   
```
plot(tree1, show.node.label=TRUE)
```
First it has a root node (n1 to n2) and second it has an node of degree 2 (node n24), which is not the root. 
The simple solution is to call this line beforehand
```
tree1 <- collapse.singles(tree1)
```
It removes both the root edge and node n24. 
Node n24 would cause an error as the edges length leading to it are not identifiable.

`drop.tip`  uses `collapses.singles` by default, it has an argument if you look at the help. That's why your code for tree2 works fine. 

Regards, 
Klaus

**Comment by mguzmann** [comment]
Thanks for taking the time!
