### ISSUE TITLE
Could USER type be defined within read.phyDat?

### ISSUE THREAD

**Issue by qifei9** [KlausVigo/phangorn#19]
I got some DNA alignments using 'X' for ambiguous nt. I tried to use 
```
a <- read.phyDat("./group_0002649_aligned.phylip", format = 'phylip', type = 'USER', levels = c('a', 'c', 'g', 't', 'x', '-'), ambiguity = c('-', 'x'))
```
to read the alignment and define the USER data type. However this run into error:
```
Error in phyDat.default(data, levels = levels, return.index = return.index,  :
  data object must contain taxa names
```
Although I found a solution:
```
a <- read.dna("./group_0002649_aligned.phylip", as.character = T)
a <- as.phyDat(a, type = 'USER', levels = c('a', 'c', 'g', 't', 'x', '-'), ambiguity = c('-', 'x'))
```
it would be much more convenient if the USER data type could be defined directly within `read.phyDat`.

---
By the way, in alignments columns involving character not in the `allLevels` (like character 'x' with `type='DNA'`) will be cut off without warning. In this case, user may get wrong result and really hard to notice that. I think it would be better to print a warning when cutting off columns.

**Comment by KlausVigo** [comment]
@qifei9 I added support for `type="USER"` https://github.com/KlausVigo/phangorn/commit/5711e2293a6115e50a85efc702c344629bc4fbf3 . The problem is that it potentially can break as it uses `read.dna` from `ape` similar as you did above.  


 I believe there is a small error in your code above and it should be like this:
`a <- as.phyDat(a, type = 'USER', levels = c('a', 'c', 'g', 't'), ambiguity = c('-', 'x'))`

You can see `attr(a, "levels")` are the column labels and `attr(a, "allLevels")` as row levels of the contrast matrix `attr(a, "contrast")`


The cutting off values is a bit tricky. I agree it should include a warning or an explicit `na.action` argument (but who reads the documentation?). In fact the behaviour is similar to  `na.action=na.omit()` which is pretty common. If you leave in the NA values than it will start hurting you as soon as you start estimating.

**Comment by qifei9** [comment]
Thank you very much @KlausVigo. That is my mistake in the code.

The problem of silently cutting off columns is that for example when column 80 is cut off, the original column 100 become column 99 and the user does not know that. Then when the user use `plotAnc(tree, anc.ml, attr(anc.ml, "index")[100])`, he will get a wrong result. The user has to know clearly about the `allLevels` of the data type and the alignments. When the sequences or alignments are from a large dataset collected from public database, this is a problem. People use various characters is sequences.

**Comment by KlausVigo** [comment]
@qifei9 `phyDat` should now return a warning if sites get deleted. Will think of something more elegant. I will improve the documentation of phyDat and `vignette("phangorn-specials") `.
