### ISSUE TITLE
tree distances for rooted trees

### ISSUE THREAD

**Issue by Graham853** [KlausVigo/phangorn#21]
KF.dist() (and perhaps other tree distances) returns a peculiar value for rooted trees. It also returns an error for 2-tip trees, but there is no reason not to calculate such a distance. See the definition in appendix A of Heled and Drummond, 2011, 
https://academic.oup.com/mbe/article/27/3/570/999753/Bayesian-Inference-of-Species-Trees-from.

I think that it can be fixed like this. Instead of simply unrooting the tree before finding the distance, a new edge with length 0 could be added at the root. This turns the tree into an unrooted tree (trifurcating at root) with an extra tip.

**Comment by KlausVigo** [comment]
Hi @Graham853, 

I updated `KF.dist()`, `RF.dist()`, `wRF.dist()` on github to always use the argument rooted (often it was ignored), default is still `rooted=FALSE`. So all the functions now require 2 tips for rooted and 3 tips for unrooted trees, see example below. 
This changes from the function from comparing bipartitions to comparing clades. It may be useful for trees from programs like Beast which are rooted, otherwise it may not align with the expectation of many users.
Robinson-Foulds is often criticized that with one SPR move one can have maximum distance, in the case of the rooted version this is also possible with re-rooting the tree.  
```
library(phangorn)
tree1 <- stree(5, "left")
tree2 <- stree(5, "right")
RF.dist(tree1, tree2)
[1] 0
RF.dist(tree1, tree2, rooted=TRUE)
[1] 6

set.seed(42)
tr1 <- rtree(2)
tr2 <- rtree(2)
KF.dist(tr1, tr2, rooted=TRUE)
[1] 0.8288639
```

Klaus
