### ISSUE TITLE
node label duplicated after midpoint

### ISSUE THREAD

**Issue by GuangchuangYu** [KlausVigo/phangorn#5]
I find midpoint return tree with duplicated node label.

```r
> tr=rtree(30)
> tr

Phylogenetic tree with 30 tips and 29 internal nodes.

Tip labels:
	t9, t17, t27, t10, t4, t18, ...

Rooted; includes branch lengths.
> tr$node.label <- paste0("X", 1:29)
> mtr <- midpoint(tr)
> lbs <- mtr$node.label
> lbs[table(lbs) > 1]
[1] "X23"
```

I check the source code. The step that generate this issue is `addConfidences.phylo`.

**Comment by GuangchuangYu** [comment]
![screenshot 2015-11-24 15 40 42](https://cloud.githubusercontent.com/assets/626539/11360689/c2554ee0-92c1-11e5-8659-f125d76b507f.png)

**Comment by KlausVigo** [comment]
Hi Guangchuang, 

thanks for your effort. Here it is a bit more complicated and it is more a feature than a bug. I intentionally (mis-)use the the node.label to store support (bootstrap) values for edges. So the two edges leading towards the root will always have the same support value as they represent the same bipartition (run the code below). Assuming you judge a split 123|456 as the same as 456|123, that's why you have duplicated values. `addConfidences` compares the bipartitions of two objects and adds the support values from the second onto the first. Storing support values in node labels is the only way to include support values in a phylo object I know of and it reads / writes nicely into the Newick format. So I suspect this is quite common use of node labels.
```{R}
library(phangorn)
data(yeast)

yeast <- subset(yeast, , 1:500, FALSE)
tree <- NJ(dist.ml(yeast))
set.seed(1)
trees <- bootstrap.phyDat(yeast, function(x)NJ(dist.ml(x)))

tree$edge.length[2] <- .05 
par(mfrow=c(1,2), mar = c(0,0,0,0))
tree <- plotBS(tree, trees, type = "u", p=0)
plot(midpoint(tree), show.node.label = TRUE)
```
The solution is to give midpoint another argument, which tells what to do with node labels. If node labels represent support values or not or even should be deleted. I will try to code this tonight, maybe you can check it if it works for you.    
A related problem is that the tree$edge matrix changes when you reroot the tree, as it is implied that the root is `number of tips + 1` (I saw ggtree has also a `getRoot` function which does not assume this). The `reorder` and `plot` functions expect this but it is not necessarily needed and `ggtree` also complains. You can easily get ripleyed if you try to touch the `reorder` function ;) It would be nice to see this requirement dropped (I have a few more wishes on my list), would make a lot of things easier and in case of rerooting node labels stay the same in your case.  

However I think it depends really what you store in the node labels. Node labels will frequently not make much sense after rerooting. For example node ages will change or if node labels contain names of clades and one reroots the tree these may not be monophyletic any more (you may want to rename or drop these).

Cheers, 
Klaus

**Comment by GuangchuangYu** [comment]
There are some newick-derived formats (i.e. [NHX](https://github.com/GuangchuangYu/ggtree/issues/27)) that support to store additional information. But these formats are not widely supported as standard newick file. It's indeed very common to store support values as node labels. 

It's not necessary to store support values in node labels. In `ggtree`, we defined `S4` classes to store `phylo` object with related evolutionary data, so that users can annotate tree easily. 

We inferred ancestral sequences and want to display some related information on the tree. At least in this scenario, node label is important since it is the linker for attaching sequence to internal node.

I have test your recent commit, it works as I expected. Thanks for your quick update.

FYI, I also update `ggtree::getRoot()`, now it perform similar to `phangorn::getRoot()`.

Best Regads,
Guangchuang
