### ISSUE TITLE
How to extract the result of pratchet() ?

### ISSUE THREAD

**Issue by Tina9** [KlausVigo/phangorn#75]
Hi KlausVigo,

I am currently working on constructing the phylogenetic tree using pratchet(). My codes are as follows:
```R
info <- read.table("Mouse.txt", row.names = 1, header = T, sep = ",")
new_info <- as.data.frame(t(info))
primates <- phyDat(new_info, type = "USER",
                   levels=c('G', 'L', 'N'), ambiguity='?')

treeRatchet <- pratchet(primates, trace = 0)
plot(treeRatchet)
```

Questions are as follows:
1. I found the result is random since I got different results many times. Is there something I made a mistake?
2. How to extract the result of pratchet? I want to know the order of the result. However, `treeRatchet$edge/Nnode/tip.label` helped nothing.

Thanks for your help at advance

**Comment by KlausVigo** [comment]
Hi @Tina9, 
your code seems ok. 

1. I found the result is random since I got different results many times. Is there something I made a mistake?

I actually get the same trees back, assuming the trees are the same if the Robinson-Foulds distance is 0:
```
treeRatchet1 <- pratchet(primates, k=100)
treeRatchet2 <- pratchet(primates, k=100)
RF.dist(treeRatchet1, treeRatchet2)
[1] 0
```
However your data seem to have few phylogenetic signal. The bootstrap support for each most edges is very low: 
```
bs <- bootstrap.phyDat(primates, pratchet)
plotBS(treeRatchet, bs, "phylogram", p=0)
``` 
the edge lengths of the trees have now meaning in this plot. 
What kind of data you are using? 

2. How to extract the result of pratchet? I want to know the order of the result. However, treeRatchet$edge/Nnode/tip.label helped nothing.

`attr(treeRatchet, "pscore")` returns the parsimony score for the ratchet tree. 
What do you mean with order?

**Comment by Tina9** [comment]
1. Yes, the value of Robinson-Foulds distance of all the results are the same. What different is sample distance. So there is many different trees with the same value of Robinson-Foulds distance. But which tree do we choose? How to decide it?

2. For extracting the result of `pratchet()`, I mean to extract the order of these samples shown on the plot. For example, which samples are closer? Using `plot(treeRatchet)` to visualize the result, how to extract the order of the samples shown on the plot.

**Comment by KlausVigo** [comment]
to 1. and 2. This means the trees are all the same, just the representation differs! 
You can change the order of the tree under certain constraints, e.g. with the rotate() or ladderize() function and the tree stays still represents the same relationships. You want to read this little [article](https://science.sciencemag.org/content/sci/310/5750/979.full.pdf) on how to interpret phylogenetic trees. 
The problem with unrooted trees like the one returned from pratechet you would need to root them for example with a known outgroup.

**Comment by Tina9** [comment]
Thanks for your help.

**Comment by KlausVigo** [comment]
Hi @Tina9, 
I close the issue. If you have further question feel free  to ask or open an issue.
