### ISSUE TITLE
Phangorn Midpoint root changing branch lengths

### ISSUE THREAD

**Issue by zomestaph** [KlausVigo/phangorn#77]
I have a question regarding midpoint rooting with Phangorn and how it is dealing with branch lengths. 
Read in a tree and after midpoint rooting and calculating the wRFdist, I get a very small value, which, I figured out after looking at the edge lengths for both the trees that midpoint rooting modifies the branch lengths at the root (subtracts from one and adds to the other). Is it appropriate to be doing that? Below is my code and example. I should also mention that topology of the trees is unaffected (RF.dist=0).
I apologize if I am not clear in my question.

 tree<-((((32:9.554e-05,((18:6.31215e-05,28:6.31215e-05):1.7101e-05,(49:3.36596e-05,(43:1.75316e-05,31:1.75316e-05):1.6128e-05):4.656275e-05):1.531785e-05):2.653515e-05,((7:5.7594e-06,6:5.7594e-06):7.095e-07,25:6.4689e-06):0.0001156065):0.000399254,((((44:9.7651e-05,11:9.7651e-05):0.000106803,(10:6.69175e-05,1:6.69175e-05):0.0001375365):0.000141065,((9:0.000133072,(((13:1.988565e-05,20:1.988565e-05):2.1104e-05,(45:1.523915e-05,5:1.523915e-05):2.575045e-05):5.303e-05,41:9.40195e-05):3.90523e-05):3.01032e-05,(39:1.246815e-05,8:1.246815e-05):0.000150707):0.000182344):0.000115363,(16:0.000103594,(15:0.0001007285,0:0.0001007285):2.865545e-06):0.0003572885):6.0447e-05):0.002071785,(((((((26:2.72224e-06,27:2.72224e-06):5.12155e-05,(36:9.4171e-06,38:9.4171e-06):4.45205e-05):0.000116724,14:0.000170662):4.48344e-05,(4:1.21263e-05,40:1.21263e-05):0.00020337):0.00059691,23:0.00081241):0.000481626,(((47:0.000228911,33:0.000228911):3.73202e-05,(35:0.000114015,(17:3.15946e-05,(21:9.5111e-06,2:9.5111e-06):2.208345e-05):8.24205e-05):0.0001522165):0.001023885,((42:0.0001248335,(19:1.69576e-06,3:1.69576e-06):0.000123138):0.000970915,34:0.00109575):0.0001943645):3.920055e-06):0.00069551,(((12:3.74662e-05,(22:1.090095e-05,37:1.090095e-05):2.65653e-05):2.30144e-05,29:6.04805e-05):0.00067469,(24:0.0001594815,(30:9.9558e-05,(46:2.97238e-05,48:2.97238e-05):6.98345e-05):5.99235e-05):0.00057569):0.001254375):0.000603575);

> set.seed(42)
tree<-read.tree("tree.newick")
New_tree<-midpoint(tree)
 wRF.dist(tree,New_tree,rooted=T)
[1] 0.000000007255

**Comment by KlausVigo** [comment]
Hi @zomestaph, 
`midpoint` puts the tree in the middle of the path between the most distance tips. 
I use `midpoint` mainly because rooted trees are sometimes nicer to plot than unrooted ones (and if the rate is constant this may be close to real root of the data).

In your case your tree is almost ultrametric. I would guess the small differences are due to rounding errors. `RF.dist()` and  `wRF.dist(tree,New_tree,rooted=FALSE)` should be 0 as the unrooted trees are identical. The differences is just where the root moves on the edge. I don't think in your case New_tree is any better than tree. 
I hope this was helpful
Regards, 
Klaus
