### ISSUE TITLE
Write ancestral reconstruction to file

### ISSUE THREAD

**Issue by surh** [KlausVigo/phangorn#93]
Is there any way to write the most ancestrally reconstructed sequences to a fasta file?

If I use `wite.phyDat` on the output of any ancestral recontruction I just get a sequences with all 'a'.

**Comment by KlausVigo** [comment]
Hi @surh , 

that should not happen.  Which version of phangorn/R are you using?
Here is some code which works on my machine.
I start with simulating a tree and an alignment.
```
library(phangorn)
tree <- rcoal(6)
plot(tree)
nodelabels()
dat <- simSeq(tree, l=15)
```
It is important to use the argument `return = "phyDat"`
```
anc <- ancestral.pars(tree, dat, return = "phyDat")
as.character(anc)
write.phyDat(anc, file = "test.fas", format = "fasta")
```
If you have problems can you send me your script and the dataset/tree if possible. 
Kind regards, 
Klaus

**Comment by surh** [comment]
It was my bad. I was using the output of ancestral reconstruction with `return="prob"`. Still, it would be nice if `write.phyDat` threw and error when this happens, instead of silently writing an incorrect file.

Sur

**Comment by KlausVigo** [comment]
No worries! I will add a check to this. 
Klaus

**Comment by DiracZhu1998** [comment]
solved already. it's prob matrix.

**Comment by KlausVigo** [comment]
Hi @DiracZhu1998, 
glad you figured it out. I am working on how to export ancestral states in a better way and also on some more tools to present them. In the development version I added an experimental function `write.ancestral` as a more or less tidy `data.frame`. The problem is that the output is not an alignment as one has probabilities for each state.
